language: node_js

node_js:
  - '0.10'

sudo: false

notifications:
  email:
    on_success: change
    on_failure: always

after_success:
  - npm install -g codeclimate-test-reporter
  - cat coverage/lcov.info | codeclimate

addons:
  code_climate:
    repo_token: 248d8b4e97709a59d23e3938cbfbe7141ba4d22e33daf62355485e581ecec1b0
